disabled_rules: # Default Rules에서 비활성화할 규칙
    
    # line의 마지막에는 빈 여백이 있으면 안됩니다.
    - trailing_whitespace
    
    # case들문 사이에는 공백이 있어야 합니다.
    - vertical_whitespace_between_cases
    
    # line의 길이를 제한합니다.
    - line_length

opt_in_rules:

    # force unwrapping을 하지 않습니다.
    - force_unwrapping
    
    # 프로퍼티의 타입을 명시해야합니다.
    - explicit_type_interface
    
    
# Options
type_body_length:
  warning: 200 # warning
  error: 400 # error
file_length:
  warning: 300
  error: 600
function_body_length:
  warning: 20
  error: 40
  
reporter: "xcode"
